### PR TITLE
Fix macOS (bash 3.2) compatibility

### PR DESCRIPTION
**Pull request by ffurrer2**
- Bash 3.2 compatibility fixed

### CODE REVIEW

**Review by ogruene — APPROVED** [review]
Checked that the scripts still run on Windows in Git Bash. Looks good to me.

**Comment by gobenja** [comment]
Hi @ffurrer2 

the old and new script version works for me.
What was the reason for your change?

testet on macOS (zsh 5.7.1 and bash 5.0.11)

**Comment by ffurrer2** [comment]
Hi @gobenja 

the reason for the change was to support the preinstalled bash (3.2.57) on masOS 10.14.6.

**Review by gobenja — APPROVED** [review]
LGTM

**Pull request merged**
